/**Copyright (C) 2013 Thomas Maher
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
package com.jimsuplee.recordlabels;

import android.app.ListActivity;
import android.app.Activity;
import android.content.Intent;
import android.widget.ListView;
import android.widget.ArrayAdapter;
import java.util.ArrayList;
import java.util.List;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.net.Uri;
import android.widget.TextView;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.view.View;
import android.util.Log;


public class Founder extends ListActivity {
	static final String TAG = "LABELS";
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
	    displayListView();
	}
	
	private void displayListView() {
		List<String> founderList = new ArrayList<String>();
	    founderList.add("A-1_C.E.O.");
	    founderList.add("Aaron Bieler");
	    founderList.add("Aaron_North");
	    founderList.add("Aaron_Turner");
	    founderList.add("Aaron_Yates");
	    founderList.add("ABS-CBN");
	    founderList.add("ABS-CBN Entertainment Group");
	    founderList.add("Adam_Pfahler");
	    founderList.add("Adam Scott");
	    founderList.add("Adrian_Orange");
	    founderList.add("Afeni_Shakur");
	    founderList.add("Ahold");
	    founderList.add("Aim_(musician)");
	    founderList.add("Akira_Kochi");
	    founderList.add("Akon");
	    founderList.add("Alan Daly");
	    founderList.add("Alan_McGee");
	    founderList.add("Alex_Felsinger");
	    founderList.add("Alex Fitzpatrick");
	    founderList.add("Alex_Julien");
	    founderList.add("Alex_Paterson");
	    founderList.add("Al Jourgensen");
	    founderList.add("Allen_Kovac");
	    founderList.add("Allison McGourty");
	    founderList.add("Alton_Abraham");
	    founderList.add("Al-Waleed_bin_Talal");
	    founderList.add("Amelia_S._Haygood");
	    founderList.add("Ammunition_Promotions");
	    founderList.add("Andrew_Fletcher_(musician)");
	    founderList.add("Andrew_James");
	    founderList.add("Andrew Penhallow");
	    founderList.add("Andrew Townsend");
	    founderList.add("Andrew Weatherall");
	    founderList.add("Andy_Blackman_Hurwitz");
	    founderList.add("Andy_Maddocks");
	    founderList.add("Angus_Keith");
	    founderList.add("Antonio_Reid");
	    founderList.add("Appleblim");
	    founderList.add("Arcangel");
	    founderList.add("Archie_Bleyer");
	    founderList.add("Arlo_Banks");
	    founderList.add("Arnaldo ");
	    founderList.add("A.R.Rahman");
	    founderList.add("Bam_Margera");
	    founderList.add("Bang_Em_Smurf");
	    founderList.add("Barry Hankerson");
	    founderList.add("Barry Hogan");
	    founderList.add("Bart Dujardin");
	    founderList.add("Beckett_&_Taylor");
	    founderList.add("Beluga");
	    founderList.add("Benedict Davies & Sean Hocking");
	    founderList.add("Ben_Hoffman");
	    founderList.add("Beni_B");
	    founderList.add("Berry_Gordy_Jr.");
	    founderList.add("Bettina_Richards");
	    founderList.add("B.G._(rapper)");
	    founderList.add("Big_Block");
	    founderList.add("Big Fase 100 ");
	    founderList.add("Bill_Drummond");
	    founderList.add("Billy_Corgan");
	    founderList.add("Billy Ray Hearn");
	    founderList.add("Bird_Williams");
	    founderList.add("Blair_Purda");
	    founderList.add("Blake Judd ");
	    founderList.add("Bob and Mary Irwin");
	    founderList.add("Bob_Marley");
	    founderList.add("Bob Schwartz");
	    founderList.add("Bob_Thomas");
	    founderList.add("Bogdan Kopec");
	    founderList.add("Bow Wow");
	    founderList.add("Bradley_Nowell");
	    founderList.add("Brad Powell");
	    founderList.add("Brad Sims");
	    founderList.add("Brad_Trew");
	    founderList.add("Brandon Ebel");
	    founderList.add("Brandon_Ebel");
	    founderList.add("Brandon Helms");
	    founderList.add("Brett_Wickens");
	    founderList.add("Brian_Ferriman");
	    founderList.add("Brian_Lowit");
	    founderList.add("Brian_Perera");
	    founderList.add("Brian Taranto");
	    founderList.add("Bruce_Lundvall");
	    founderList.add("Bruce Milne");
	    founderList.add("Bud Schaetzle");
	    founderList.add("Busta_Rhymes");
	    founderList.add("Camron (Founder)");
	    founderList.add("Candice_Pederson");
	    founderList.add("Carl Emery");
	    founderList.add("Carl_Jefferson");
	    founderList.add("Carl Morris");
	    founderList.add("Carl Severson");
	    founderList.add("Carter Matschullat");
	    founderList.add("Casey_Horrigan");
	    founderList.add("CeCe_Winans");
	    founderList.add("Cecil_Holmes");
	    founderList.add("Cees_Wessels");
	    founderList.add("CEO_DMAK");
	    founderList.add("Chamillionaire");
	    founderList.add("Chase_Stain");
	    founderList.add("Chingo_Bling");
	    founderList.add("Chingy");
	    founderList.add("Chris Berry");
	    founderList.add("Chris_Blackwell");
	    founderList.add("Chris_Broach");
	    founderList.add("Chris_Cutler");
	    founderList.add("Chris_Gotti");
	    founderList.add("Chris_Hewitt");
	    founderList.add("Chris Lombardi");
	    founderList.add("Chris Murphy");
	    founderList.add("Chris_Randall_(musician)");
	    founderList.add("Chris Renegade");
	    founderList.add("Chris_Stamp");
	    founderList.add("Chris Swanson");
	    founderList.add("Chris Takino");
	    founderList.add("Christof Ellinghaus");
	    founderList.add("Christopher Possanza");
	    founderList.add("Christopher Watson");
	    founderList.add("Chris_Wu");
	    founderList.add("Chrysalis_Group");
	    founderList.add("Chuck_Phelps");
	    founderList.add("Chuck_Smith_(pastor)");
	    founderList.add("Clarence_Avant");
	    founderList.add("Clipse");
	    founderList.add("Clive_Calder");
	    founderList.add("Clive_Davis");
	    founderList.add("Collective_Soul");
	    founderList.add("Comedy_Central");
	    founderList.add("Concord_Dawn");
	    founderList.add("Corey_Rusk");
	    founderList.add("Corey Taylor");
	    founderList.add("Crass");
	    founderList.add("Creed_Taylor");
	    founderList.add("Daddy_Yankee");
	    founderList.add("Damon_Albarn");
	    founderList.add("Damon_Forbes");
	    founderList.add("Dan Haines");
	    founderList.add("Daniel Catullo");
	    founderList.add("Daniel_Piotrowski");
	    founderList.add("Daniel_Waldner");
	    founderList.add("Dan_Koplowitz");
	    founderList.add("Danny Schur");
	    founderList.add("Dan_Osborn");
	    founderList.add("Dan_Popplewell");
	    founderList.add("Dan_Prothero");
	    founderList.add("Dan_the_Automator");
	    founderList.add("Dario_Soria");
	    founderList.add("Darius Van Arman");
	    founderList.add("Darren Bowls");
	    founderList.add("Darren_Ockert");
	    founderList.add("Darryl Rodway & Janusz Jarosinski");
	    founderList.add("Daundadogg");
	    founderList.add("Dave_Crider");
	    founderList.add("Dave_Kaplan");
	    founderList.add("Dave Kelly (Producer)");
	    founderList.add("Dave_Piccioni");
	    founderList.add("Dave Rees");
	    founderList.add("David_Elliott_(musician)");
	    founderList.add("David_Foster");
	    founderList.add("David_Geffen");
	    founderList.add("David Greene");
	    founderList.add("David_Grisman");
	    founderList.add("David_Hayes_(record_producer)");
	    founderList.add("David_Porky_Brennand");
	    founderList.add("David Suff");
	    founderList.add("David Williams");
	    founderList.add("Daz_Dillinger");
	    founderList.add("D-Block");
	    founderList.add("D-Bo");
	    founderList.add("DCT");
	    founderList.add("Deacon Ronald K. Stein");
	    founderList.add("Dean_Martin");
	    founderList.add("Dee Robb");
	    founderList.add("Dennis Remmer and Anna Petrou");
	    founderList.add("Devyne Stephens");
	    founderList.add("DiABol");
	    founderList.add("Digby_Pearson");
	    founderList.add("DJ_Bomberjack");
	    founderList.add("DJ_Clue");
	    founderList.add("DJ_Crucial");
	    founderList.add("DJ_Iguana");
	    founderList.add("DJ_Kay_Slay");
	    founderList.add("DJ_Nelson");
	    founderList.add("DJ_Rhettmatic");
	    founderList.add("Doctor_Dread");
	    founderList.add("Dominic Brown");
	    founderList.add("Donna_Dresch");
	    founderList.add("Don_Omar");
	    founderList.add("Don_Rose_(Rykodisc)");
	    founderList.add("Doug Morris");
	    founderList.add("Dr._Dre");
	    founderList.add("Dru-Ha");
	    founderList.add("Duncan Browne");
	    founderList.add("Dwayne Goettel");
	    founderList.add("dw_Norton");
	    founderList.add("E-40");
	    founderList.add("East_Bay_Ray");
	    founderList.add("Eddie_OLoughlin");
	    founderList.add("Edward_Lewis_(Decca)");
	    founderList.add("Eiichi Naito");
	    founderList.add("Eldridge_R._Johnson");
	    founderList.add("Elias de Leon");
	    founderList.add("Elijah_Wood");
	    founderList.add("Emile_Berliner");
	    founderList.add("Enrique Soissa");
	    founderList.add("Eric_Friedl");
	    founderList.add("Eric_Gallo");
	    founderList.add("Erick_Morillo");
	    founderList.add("Ericson_Alexander_Molano");
	    founderList.add("Erik_Koppin");
	    founderList.add("Estelle_Axton");
	    founderList.add("Fatboy_Slim");
	    founderList.add("Fat_Joe");
	    founderList.add("Fat_Mike");
	    founderList.add("Felix_Havoc");
	    founderList.add("Florence Greenberg");
	    founderList.add("Francis Daniel");
	    founderList.add("Frank_DAngelo");
	    founderList.add("Fraser Armstrong");
	    founderList.add("Fred_Frith");
	    founderList.add("Fred_Munao");
	    founderList.add("Fred Oxon");
	    founderList.add("Fredrick W. Horn");
	    founderList.add("Gary Richards");
	    founderList.add("Gene Norman");
	    founderList.add("Geoff Goddard");
	    founderList.add("Geoff_Kresge");
	    founderList.add("George Goldner");
	    founderList.add("Gerry Leiske");
	    founderList.add("Giacomo Pelliciotti");
	    founderList.add("Gildas Loa");
	    founderList.add("Gilles_Peterson");
	    founderList.add("Gilson Rodrigues");
	    founderList.add("Giulio Tedeschi");
	    founderList.add("Gladys_Pizarro");
	    founderList.add("Glenn A. Baker");
	    founderList.add("Glenn_Branca");
	    founderList.add("Glenn_Danzig");
	    founderList.add("Glenn Dicker");
	    founderList.add("G.M.S.");
	    founderList.add("Gordon Henderson ");
	    founderList.add("Greg_Ginn");
	    founderList.add("Greg_Shaw");
	    founderList.add("Greg_Werckman");
	    founderList.add("Halo_of_Flies");
	    founderList.add("Hanin_Elias");
	    founderList.add("Harry_Stinson_(musician)");
	    founderList.add("Hector_El_Father");
	    founderList.add("Heikki_Vilenius");
	    founderList.add("Herb_Abramson");
	    founderList.add("Hideto_Matsumoto");
	    founderList.add("Hieroglyphics_(band)");
	    founderList.add("Hiroshi Tomioka");
	    founderList.add("Holger_Petersen");
	    founderList.add("Horst Weidenm");
	    founderList.add("Hysear Randell");
	    founderList.add("Ian_Levine");
	    founderList.add("Ian_M._Anderson_(musician)");
	    founderList.add("Ice Cube");
	    founderList.add("Ido Yaron (DJ Ido)");
	    founderList.add("Insane_Clown_Posse");
	    founderList.add("Irving Green");
	    founderList.add("Itzik Alsheikh & Ronny Brown");
	    founderList.add("Ivo_Watts-Russell");
	    founderList.add("Jac_Holzman");
	    founderList.add("Jacqui_Rice");
	    founderList.add("James Boyle");
	    founderList.add("James_Diener");
	    founderList.add("James Endeacott");
	    founderList.add("James Kempner");
	    founderList.add("James_Mattern");
	    founderList.add("James_Oldham");
	    founderList.add("James_Smith_(record_executive)");
	    founderList.add("Jamie Farrell.");
	    founderList.add("Janne Granberg");
	    founderList.add("Jared_Dobias");
	    founderList.add("Jars_of_Clay");
	    founderList.add("Jason Flom");
	    founderList.add("Jason_Geter");
	    founderList.add("Jason_Schwartz");
	    founderList.add("Jay Dawson");
	    founderList.add("Jay-Z ");
	    founderList.add("Jay_Zimmermann");
	    founderList.add("Jazze_Pha");
	    founderList.add("Jeanette_Lee");
	    founderList.add("Jebediah & Naked Ape Management");
	    founderList.add("Jeff Anderson");
	    founderList.add("Jeff_Barrett");
	    founderList.add("Jeff_Mangum");
	    founderList.add("Jeff_Nelson_(musician)");
	    founderList.add("Jeff_Price");
	    founderList.add("Jeffrey Remedios");
	    founderList.add("Jeff_Rosenstock");
	    founderList.add("Jenny Toomey ");
	    founderList.add("Jeremy_deVine");
	    founderList.add("Jeremy_Weiss");
	    founderList.add("Jermaine_Dupri");
	    founderList.add("Jerry_Heller");
	    founderList.add("Jerry_Masucci");
	    founderList.add("Jerry_Moss");
	    founderList.add("Jerry Schoenbaum");
	    founderList.add("Jerry Toger");
	    founderList.add("J-Hood_(rapper)");
	    founderList.add("Jim Callon");
	    founderList.add("Jim_Jupp");
	    founderList.add("Jim West");
	    founderList.add("Jody_Bleyle");
	    founderList.add("Joe_Bataan");
	    founderList.add("Joe_Boyd");
	    founderList.add("Joel Amaretto");
	    founderList.add("Joe Sib & Bill Armstrong");
	    founderList.add("Joey_DeMaio");
	    founderList.add("John Askew");
	    founderList.add("John Chiong");
	    founderList.add("John Engelbrekt");
	    founderList.add("John_Fry");
	    founderList.add("John_Kirtland");
	    founderList.add("John_Loder");
	    founderList.add("John_Malm");
	    founderList.add("Johnny_Mercer");
	    founderList.add("John_ODonnell");
	    founderList.add("John_Watson_(artist)");
	    founderList.add("Jonathan_Galkin");
	    founderList.add("Jonathan_More");
	    founderList.add("Jonathan_Poneman");
	    founderList.add("Jon Bartlett");
	    founderList.add("Jon Hebb");
	    founderList.add("Jon Hope");
	    founderList.add("Jon_Pearce");
	    founderList.add("Jordan Cooper & Ray Cappo");
	    founderList.add("Jordan_Snodgrass");
	    founderList.add("Jord_Samolesky");
	    founderList.add("Josh Deutsch");
	    founderList.add("Joshua_Lemay");
	    founderList.add("Juggy_Gales");
	    founderList.add("Jules_Normington");
	    founderList.add("Justin Mitchell");
	    founderList.add("Justin_Oberst");
	    founderList.add("Justin_Smith");
	    founderList.add("Justin_Timberlake");
	    founderList.add("Juvenile_(rapper)");
	    founderList.add("J-vibe");
	    founderList.add("Kaada");
	    founderList.add("Kal_Mann");
	    founderList.add("Kamel Pratt and Jin");
	    founderList.add("Kanye_West");
	    founderList.add("Karl Hyde");
	    founderList.add("Kehinde ");
	    founderList.add("Ken Cheppaikode");
	    founderList.add("Kenneth_Edmonds");
	    founderList.add("Kenny_Chow");
	    founderList.add("Kevin Day");
	    founderList.add("Kevin_Douch");
	    founderList.add("Kevin_Kookogey");
	    founderList.add("Kevin Michael McKeehan  AKA tobyMac");
	    founderList.add("Kevin_Zinger");
	    founderList.add("King Leo III");
	    founderList.add("Kode9");
	    founderList.add("Korda_Marshall");
	    founderList.add("Kristian Kotarac");
	    founderList.add("Larry_Norman");
	    founderList.add("Larry Robinson ");
	    founderList.add("Lars-Olof Gustavsson and Keith Knox");
	    founderList.add("Lateef");
	    founderList.add("Laura_Ballance");
	    founderList.add("Lawrence_Mikkelsen");
	    founderList.add("Lawrence_Welk");
	    founderList.add("Lee Gopthal");
	    founderList.add("Leevan Macomeau");
	    founderList.add("Leila_Bela");
	    founderList.add("Leon Alexander and Steve Satterthwaite");
	    founderList.add("Leon_Lai");
	    founderList.add("Leslie_Moonves");
	    founderList.add("Lew Chudd");
	    founderList.add("Liam Howlett");
	    founderList.add("Lil_Romeo");
	    founderList.add("Lil_Wayne");
	    founderList.add("Lio_Cerezo");
	    founderList.add("Long_Gone_John");
	    founderList.add("Loreena_McKennitt");
	    founderList.add("Louis OReilly");
	    founderList.add("Lucas Abela");
	    founderList.add("Ludacris ");
	    founderList.add("Luiz_Calanca");
	    founderList.add("Luke Stidson");
	    founderList.add("Luny_Tunes");
	    founderList.add("Lynda_West");
	    founderList.add("Mac Dre ");
	    founderList.add("Mack_10");
	    founderList.add("Mana_(musician)");
	    founderList.add("Marcus_DL_Siskind");
	    founderList.add("Marianne_Roney");
	    founderList.add("Mario VI");
	    founderList.add("Mark Cavener");
	    founderList.add("Mark Fischer & Rob Syers");
	    founderList.add("Mark_Kozelek");
	    founderList.add("Mark Nawara");
	    founderList.add("Mark_Rae");
	    founderList.add("Mark Sommer");
	    founderList.add("Markus_Riedler");
	    founderList.add("Markus_Staiger");
	    founderList.add("Marlon ");
	    founderList.add("Martin Pollard");
	    founderList.add("Martin_Tamburovich");
	    founderList.add("Martin_Toher");
	    founderList.add("Masta_Ace");
	    founderList.add("Master_P");
	    founderList.add("Mat Domber");
	    founderList.add("Matt_Anderson");
	    founderList.add("Matt Boylan");
	    founderList.add("Matt Flood");
	    founderList.add("Matt_Haynes");
	    founderList.add("Matthew Nettleton");
	    founderList.add("Matthew St-Germaine");
	    founderList.add("Matthias Winckelmann");
	    founderList.add("Matt_Jacobson");
	    founderList.add("Matt Schwartz");
	    founderList.add("Matt Wardle");
	    founderList.add("Max_Margulis");
	    founderList.add("Max_Ward");
	    founderList.add("mc_chris");
	    founderList.add("MC_Tunes");
	    founderList.add("M.Dante");
	    founderList.add("Mehdi_Safa");
	    founderList.add("MF_Grimm");
	    founderList.add("Michael_Barnett");
	    founderList.add("Michael Blanton");
	    founderList.add("Michael Gira");
	    founderList.add("Michael Koch");
	    founderList.add("Michael Maley / Patrick Maley");
	    founderList.add("Mick Brown");
	    founderList.add("Miguel Gonzalez");
	    founderList.add("Mike_Curb");
	    founderList.add("Mike_Fisher");
	    founderList.add("Mike Levon");
	    founderList.add("Mike_Weiss");
	    founderList.add("Nas_(rapper)");
	    founderList.add("Nathan Moore");
	    founderList.add("Ncut");
	    founderList.add("Necro_(rapper)");
	    founderList.add("Neil_Burke");
	    founderList.add("Neurosis_(band)");
	    founderList.add("Nick_Cannon");
	    founderList.add("Nik Tropiano");
	    founderList.add("Nitti_(producer)");
	    founderList.add("Noah Tutak & Flynn Atkins");
	    founderList.add("Noktu");
	    founderList.add("Norman_Granz");
	    founderList.add("OG_Ron_C");
	    founderList.add("Ojo_Taylor");
	    founderList.add("Oliver Rosch");
	    founderList.add("Ollie Olsen");
	    founderList.add("Orville Campbell");
	    founderList.add("Ozi Batla");
	    founderList.add("Paris_Hilton");
	    founderList.add("Pat_Dubar");
	    founderList.add("Paul_Cox");
	    founderList.add("Paul Croan");
	    founderList.add("Paul Cullen");
	    founderList.add("Paul_Dubois");
	    founderList.add("Paul_Elstak");
	    founderList.add("Paul_Levinson");
	    founderList.add("Paul_Nunda");
	    founderList.add("Paul_Piticco");
	    founderList.add("Paul_Rickholt");
	    founderList.add("Paul Ring");
	    founderList.add("Paul_Rosenberg_(music_manager)");
	    founderList.add("Pedro(rapper)");
	    founderList.add("Per_Granberg");
	    founderList.add("Pete_Bangert");
	    founderList.add("Pete_Lawrence");
	    founderList.add("Peter_Christopherson");
	    founderList.add("Peter_Grant_(music_manager)");
	    founderList.add("Peter_Meininger");
	    founderList.add("Peter M. Kersten");
	    founderList.add("Peter_Rehberg");
	    founderList.add("Peter Walmsley");
	    founderList.add("Pharrell_Williams");
	    founderList.add("Philip_Morland");
	    founderList.add("Philippe_Galliano");
	    founderList.add("Phillip Stevens");
	    founderList.add("Phuq");
	    founderList.add("Pierre_Barouh");
	    founderList.add("Pimp_C");
	    founderList.add("PJ Crittenden");
	    founderList.add("Polow_Da_Don");
	    founderList.add("Pretty_Ricky");
	    founderList.add("Proof_(rapper)");
	    founderList.add("Q.L. Steiren");
	    founderList.add("Rami Hippi");
	    founderList.add("Randy Chortkoff");
	    founderList.add("Randy Layton");
	    founderList.add("Raphy_Pina");
	    founderList.add("Rasaq");
	    founderList.add("Ray Danniels");
	    founderList.add("Ray Harris");
	    founderList.add("Ray_J");
	    founderList.add("Raymond Termini");
	    founderList.add("Red_Jerry");
	    founderList.add("Reijo_Kiilunen");
	    founderList.add("Remote_Control_Records");
	    founderList.add("RGK_Entertainment_Group");
	    founderList.add("R. Harlan Smith");
	    founderList.add("Richard Andrew");
	    founderList.add("Richard_Branson");
	    founderList.add("Richard_Foos");
	    founderList.add("Richard_Jones");
	    founderList.add("Richard_Lyons");
	    founderList.add("Richard_Weize");
	    founderList.add("Rich_Egan");
	    founderList.add("Richie_Hawtin");
	    founderList.add("Rick_Rubin");
	    founderList.add("Ric Melia");
	    founderList.add("Robb_Johnson");
	    founderList.add("Robert_Chan");
	    founderList.add("Robert_Ellis_Orrall");
	    founderList.add("Robert_Luis");
	    founderList.add("Robert Renock");
	    founderList.add("Robert_Stigwood");
	    founderList.add("Rob_Sutcliffe");
	    founderList.add("Robyn");
	    founderList.add("Robyn_St_Clare");
	    founderList.add("Rollo_Armstrong");
	    founderList.add("Ronald Clarke");
	    founderList.add("Ronald_Slim_Williams");
	    founderList.add("Ron Clapper");
	    founderList.add("Ron_Griffin");
	    founderList.add("Ronnie_Dashev");
	    founderList.add("Ronnie_Martin");
	    founderList.add("Ross Tones");
	    founderList.add("Roy_Jones");
	    founderList.add("Rui Da Silva");
	    founderList.add("Russell_Simmons");
	    founderList.add("Rusty_Hopkinson");
	    founderList.add("Ryan_Leslie");
	    founderList.add("Sam_Berger");
	    founderList.add("Sam_Phillips");
	    founderList.add("Samuel Durling");
	    founderList.add("Samuel Valenti IV");
	    founderList.add("San_Quinn");
	    founderList.add("Sav Remzi");
	    founderList.add("Scott_Storch");
	    founderList.add("Sean_Combs");
	    founderList.add("Sean Price");
	    founderList.add("Serj_Tankian");
	    founderList.add("Seymour_Solomon");
	    founderList.add("Seymour Stein");
	    founderList.add("Shabs Jobanputra");
	    founderList.add("Sha_Money_XL");
	    founderList.add("Shaun_Tallamy");
	    founderList.add("Shawn Carter (aka Jay-Z)");
	    founderList.add("Shawn_Crahan");
	    founderList.add("Shawn_Mims");
	    founderList.add("Sheist Bub");
	    founderList.add("Sherman_Willmott");
	    founderList.add("Shiham_Samsudeen");
	    founderList.add("Sim_Lister");
	    founderList.add("Simon Foster ");
	    founderList.add("Simon_Waronker");
	    founderList.add("Skip Groff");
	    founderList.add("Skydiggers");
	    founderList.add("Slim_Moon");
	    founderList.add("Snoop_Dogg");
	    founderList.add("Solitair");
	    founderList.add("Sonny_Kay");
	    founderList.add("Soulja_Boy");
	    founderList.add("S._Shankar");
	    founderList.add("Stan_Rogers");
	    founderList.add("Steen_Thottrup");
	    founderList.add("Stefanie_Reines");
	    founderList.add("Stephen_Connolly");
	    founderList.add("Stereolab");
	    founderList.add("Steve_Aoki");
	    founderList.add("Steve Barrow");
	    founderList.add("Steve Beckett");
	    founderList.add("Steve_Drath");
	    founderList.add("Steve Gottlieb");
	    founderList.add("Steven Ehrlick");
	    founderList.add("Steven_Joerg");
	    founderList.add("Steve_Pavlovic");
	    founderList.add("Steve Rifkind");
	    founderList.add("Steve_Rifkind");
	    founderList.add("Steve Schroeder");
	    founderList.add("Steve_Shelley");
	    founderList.add("Steve Stavrakis");
	    founderList.add("Street_Dogs");
	    founderList.add("Suge_Knight");
	    founderList.add("Supermercados_Peruanos");
	    founderList.add("Suzy_Shaw");
	    founderList.add("Switchfoot");
	    founderList.add("Swizz_Beatz");
	    founderList.add("Syd_Nathan");
	    founderList.add("Talamasca_(group)");
	    founderList.add("Talib_Kweli");
	    founderList.add("Tammy_Rae_Carland");
	    founderList.add("Ted Albert");
	    founderList.add("Ted_Field");
	    founderList.add("Tego_Calderon");
	    founderList.add("Terry Farley");
	    founderList.add("Thau");
	    founderList.add("The_4-Skins#Band_members");
	    founderList.add("The_Beatles");
	    founderList.add("The_Bouncing_Souls");
	    founderList.add("The Cross Movement");
	    founderList.add("The_Delgados");
	    founderList.add("The_Dogg");
	    founderList.add("The John Reed Club");
	    founderList.add("The Maloof family");
	    founderList.add("Theodore_Ted_Green");
	    founderList.add("The_Prophet");
	    founderList.add("The_Roaring_Twenties_(band)");
	    founderList.add("The_Scientist");
	    founderList.add("Thomas_Jaldemark");
	    founderList.add("Thom Hazaert");
	    founderList.add("Three_6_Mafia");
	    founderList.add("Thurston_Moore");
	    founderList.add("Tim_Armstrong");
	    founderList.add("Timbaland");
	    founderList.add("Tim Palmer");
	    founderList.add("Tina_Casale");
	    founderList.add("Tirren Staaf");
	    founderList.add("Toby_Jeg");
	    founderList.add("Tom_Anderson_(MySpace)");
	    founderList.add("Tom Bradley");
	    founderList.add("Tom Derr");
	    founderList.add("Tom Edwards ");
	    founderList.add("Tom_Hingley");
	    founderList.add("Tom_Howard_(musician)");
	    founderList.add("Tom Larnach-Jones");
	    founderList.add("Tom Majerczak");
	    founderList.add("Tommi Forsstr");
	    founderList.add("Tom_Silverman");
	    founderList.add("Tone & Nigel");
	    founderList.add("Tony Brummel");
	    founderList.add("Tony_Dewald");
	    founderList.add("Tony Morley");
	    founderList.add("Travis Dickerson");
	    founderList.add("Travis Higdon");
	    founderList.add("Travis_McCoy");
	    founderList.add("Trevor_Horn");
	    founderList.add("Trevor_Jackson");
	    founderList.add("Trey_Anastasio");
	    founderList.add("unknown");
	    founderList.add("variable");
	    founderList.add("Vartan Avenassian");
	    founderList.add("Vincent ");
	    founderList.add("Vin_Diesel");
	    founderList.add("Vinnie_Fiorello");
	    founderList.add("Vinnie_Paul");
	    founderList.add("Virgin_Records");
	    founderList.add("Waah_Dean");
	    founderList.add("Walt_Disney");
	    founderList.add("Warren Clark");
	    founderList.add("Warren_G");
	    founderList.add("Warren_Haynes");
	    founderList.add("Will_Ashon");
	    founderList.add("Will_Butler");
	    founderList.add("Will_Hackney");
	    founderList.add("will.i.am");
	    founderList.add("William Lei Li");
	    founderList.add("William_Socolov");
	    founderList.add("Wish_Bone");
	    founderList.add("Wisin_&_Yandel");
	    founderList.add("Wolfgang Voigt");
	    founderList.add("Wolfram Eckert");
	    founderList.add("Xzibit");
	    founderList.add("Yannick Lorraine");
	    founderList.add("Yoshiki_(musician)");
	    founderList.add("Young_Buck");
	    founderList.add("Yukmouth");
	    founderList.add("Zach_Feldberg");
	    founderList.add("Zac Pennington");
	    founderList.add("Zion_y_Lennox");
	    
	    // create an ArrayAdaptar from the String Array
    	ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this, R.layout.locationtextview, founderList);
	    setListAdapter(dataAdapter);
	    ListView listView = getListView();
	    // enables filtering for the contents of the given ListView
	    listView.setTextFilterEnabled(true);
	    listView.setOnItemClickListener(new OnItemClickListener() {
		    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
			    Intent i = new Intent("");
			    String founderChoice = ((TextView) view).getText().toString();
			    i.setData(Uri.parse(founderChoice));
			    setResult(RESULT_OK, i);
		    	finish();
		    }
    	});
    }
}

