package com.jimsuplee.recordlabels;

import android.app.ListActivity;
import android.app.Activity;
import android.content.Intent;
import android.widget.ListView;
import android.widget.ArrayAdapter;
import java.util.ArrayList;
import java.util.List;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.net.Uri;
import android.widget.TextView;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.view.View;
import android.util.Log;

public class Genre  extends ListActivity {
	static final String TAG = "LABELS";
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
	    displayListView();
	}
	
	private void displayListView() {
		List<String> genreList = new ArrayList<String>();
	    genreList.add("1960s");
	    genreList.add("Acid House");
	    genreList.add("Acid_House");
	    genreList.add("Acoustic_Rock");
	    genreList.add("Adult Contemporary");
	    genreList.add("All");
	    genreList.add("Alternative");
	    genreList.add("Alternative_Christian_music");
	    genreList.add("Alternative_Metal");
	    genreList.add("Alternative_music");
	    genreList.add("Alternative_Music");
	    genreList.add("Alternative_rock");
	    genreList.add("Alternative_Rock");
	    genreList.add("Ambient");
	    genreList.add("Ambient_music");
	    genreList.add("American_folk_music");
	    genreList.add("Anarcho-punk");
	    genreList.add("Arabic_Music");
	    genreList.add("Avant-garde");
	    genreList.add("Avant_Garde");
	    genreList.add("Avant-garde_jazz");
	    genreList.add("Balearic");
	    genreList.add("Big_beat");
	    genreList.add("Black_Metal");
	    genreList.add("Bluegrass_music");
	    genreList.add("blues");
	    genreList.add("Blues");
	    genreList.add("Blues_music");
	    genreList.add("Breakstep");
	    genreList.add("British folk and folk rock");
	    genreList.add("Britpop");
	    genreList.add("Cantopop");
	    genreList.add("Chillout");
	    genreList.add("Chiptune");
	    genreList.add("Christian");
	    genreList.add("Christian_Hip_hop");
	    genreList.add("Christian_metal");
	    genreList.add("Christian_Metalcore");
	    genreList.add("Christian music");
	    genreList.add("Christian_music");
	    genreList.add("Christian_Music");
	    genreList.add("Christian_Rap");
	    genreList.add("Christian_rock");
	    genreList.add("Classic");
	    genreList.add("Classical_music");
	    genreList.add("Classical_Music");
	    genreList.add("Classic_Rock");
	    genreList.add("Comedy");
	    genreList.add("Comic_books");
	    genreList.add("Contemporary_Christian");
	    genreList.add("Contemporary_Christian_music");
	    genreList.add("Contemporary_R&B");
	    genreList.add("country");
	    genreList.add("Country");
	    genreList.add("country_music");
	    genreList.add("Country_music");
	    genreList.add("Dance");
	    genreList.add("Dancehall");
	    genreList.add("Dance_music");
	    genreList.add("Dance_Music");
	    genreList.add("Dar_ambient");
	    genreList.add("Dark_cabaret");
	    genreList.add("Dark_Wave");
	    genreList.add("Deathcore");
	    genreList.add("Death_metal");
	    genreList.add("Death_Metal");
	    genreList.add("Digital_hardcore");
	    genreList.add("Dirty_South");
	    genreList.add("Disco");
	    genreList.add("Doom_metal");
	    genreList.add("Drone_music");
	    genreList.add("Drum_and_Bass");
	    genreList.add("Drum and bass/ Avant garde");
	    genreList.add("Drumnbass");
	    genreList.add("Dub_music");
	    genreList.add("Dubstep");
	    genreList.add("EBM");
	    genreList.add("Electroacoustic_music");
	    genreList.add("Electro-hop");
	    genreList.add("electronic");
	    genreList.add("Electronic");
	    genreList.add("Electronica");
	    genreList.add("Electronic_music");
	    genreList.add("Electronic_Music");
	    genreList.add("Electropop");
	    genreList.add("Ethereal_Wave");
	    genreList.add("European_classical_music");
	    genreList.add("European_Classical_Music");
	    genreList.add("Experimental_music");
	    genreList.add("Experimental_Music");
	    genreList.add("Experimental_Rock");
	    genreList.add("Extreme_metal");
	    genreList.add("Feminist");
	    genreList.add("Film Soundtracks");
	    genreList.add("Folk");
	    genreList.add("Folk_music");
	    genreList.add("Folk rock");
	    genreList.add("Folk_rock");
	    genreList.add("Folk-rock");
	    genreList.add("Folk-Rock");
	    genreList.add("Funk_music");
	    genreList.add("Futurepop");
	    genreList.add("Gabber");
	    genreList.add("Gangsta_rap");
	    genreList.add("Gangsta_Rap");
	    genreList.add("Garage_rock");
	    genreList.add("Garage Rock");
	    genreList.add("Garage_Rock");
	    genreList.add("Genge");
	    genreList.add("Gospel");
	    genreList.add("gospel_music");
	    genreList.add("Gospel_music");
	    genreList.add("Grass roots");
	    genreList.add("Grindcore");
	    genreList.add("Grunge");
	    genreList.add("guitar-oriented");
	    genreList.add("Hardcore");
	    genreList.add("Hardcore_punk");
	    genreList.add("Hardcore_Punk");
	    genreList.add("Hardhouse");
	    genreList.add("hard_rock");
	    genreList.add("Hard_rock");
	    genreList.add("Hard_Rock");
	    genreList.add("Hardstyle");
	    genreList.add("Heavy_metal");
	    genreList.add("Heavy Metal");
	    genreList.add("Heavy_Metal");
	    genreList.add("Heavy_metal_music");
	    genreList.add("Hi-NRG");
	    genreList.add("Hip_hop");
	    genreList.add("Hip-hop");
	    genreList.add("Hip Hop");
	    genreList.add("Hip_Hop");
	    genreList.add("Hip-Hop");
	    genreList.add("hip_hop_music");
	    genreList.add("Hip_hop_music");
	    genreList.add("Hip-hop_music");
	    genreList.add("Hip_Hop_music");
	    genreList.add("Hip-Hop_music");
	    genreList.add("Hip_Hop_Music");
	    genreList.add("historic) various");
	    genreList.add("(historic) Various");
	    genreList.add("Historic: Various ");
	    genreList.add("Horrorcore");
	    genreList.add("House_music");
	    genreList.add("House_Music");
	    genreList.add("Hyphy");
	    genreList.add("Indie");
	    genreList.add("Indie ");
	    genreList.add("Indie_folk");
	    genreList.add("indie_music");
	    genreList.add("Indie_music");
	    genreList.add("Indie_(music)");
	    genreList.add("Indie_pop");
	    genreList.add("Indie_Pop");
	    genreList.add("indie rock");
	    genreList.add("indie_rock");
	    genreList.add("Indie rock");
	    genreList.add("Indie_rock");
	    genreList.add("Indie_Rock");
	    genreList.add("Industrial");
	    genreList.add("Industrial_music");
	    genreList.add("Industrial_Music");
	    genreList.add("Industrial_rock");
	    genreList.add("Instrumental");
	    genreList.add("Instrumental_rock");
	    genreList.add("Intelligent_dance_music");
	    genreList.add("jazz");
	    genreList.add("Jazz");
	    genreList.add("Jazz / World");
	    genreList.add("J-Pop");
	    genreList.add("Jumpstyle");
	    genreList.add("Latin");
	    genreList.add("Latin Alternative");
	    genreList.add("Library_music");
	    genreList.add("Melodic_psytrance");
	    genreList.add("Merseybeat");
	    genreList.add("metal");
	    genreList.add("Metal");
	    genreList.add("Metalcore");
	    genreList.add("Metal_music");
	    genreList.add("Metal_(music)");
	    genreList.add("Mexican_Rap");
	    genreList.add("Microhouse");
	    genreList.add("Midwest_hip_hop");
	    genreList.add("Minimal");
	    genreList.add("Minimal_techno");
	    genreList.add("Modern_rock");
	    genreList.add("Motown");
	    genreList.add("Musical_theatre");
	    genreList.add("Music_genre");
	    genreList.add("Music_of_India");
	    genreList.add("Neoclassical");
	    genreList.add("Nerdcore");
	    genreList.add("New_Age_music");
	    genreList.add("Noise_music");
	    genreList.add("Noise_rock");
	    genreList.add("Nu_jazz");
	    genreList.add("Old_school_hip_hop");
	    genreList.add("Orchestral");
	    genreList.add("Ottoman_classical_music");
	    genreList.add("Outsider_music");
	    genreList.add("Persian_pop_music");
	    genreList.add("Pop");
	    genreList.add("Pop/Indie");
	    genreList.add("Pop music");
	    genreList.add("Pop_music");
	    genreList.add("Pop_punk");
	    genreList.add("Pop-Punk");
	    genreList.add("Pop & Rock.");
	    genreList.add("Popular_music");
	    genreList.add("Positive/Inspirational Hip Hop and R&B");
	    genreList.add("Post-hardcore");
	    genreList.add("Post_Hardcore");
	    genreList.add("Post-Hardcore");
	    genreList.add("Post-punk");
	    genreList.add("Post_rock");
	    genreList.add("Post-rock");
	    genreList.add("Power_metal");
	    genreList.add("Power_Metal");
	    genreList.add("progressive_house");
	    genreList.add("Progressive_House");
	    genreList.add("progressive_rock");
	    genreList.add("Progressive_Trance");
	    genreList.add("Psybient");
	    genreList.add("Psychedelic_pop");
	    genreList.add("Psychedelic_trance");
	    genreList.add("Psych_Folk");
	    genreList.add("Psy-trance");
	    genreList.add("Punk");
	    genreList.add("Punk/Indie/Pop");
	    genreList.add("Punk rock");
	    genreList.add("Punk_rock");
	    genreList.add("Punk_Rock");
	    genreList.add("Queercore");
	    genreList.add("Rap");
	    genreList.add("Rap_Music");
	    genreList.add("R&B");
	    genreList.add("Reggae");
	    genreList.add("Reggaeton");
	    genreList.add("Reggaeton and Hip-Hop");
	    genreList.add("Retail");
	    genreList.add("Rhythm_and_blues");
	    genreList.add("Rhythm_and_Blues");
	    genreList.add("Ril");
	    genreList.add("Riot_Grrrl");
	    genreList.add("Rock");
	    genreList.add("rock_and_roll");
	    genreList.add("Rock_and_Roll");
	    genreList.add("rock_music");
	    genreList.add("Rock_music");
	    genreList.add("Rock_(music)");
	    genreList.add("Rock/Punk_Rock/Indie_Rock/Fusion_Rock");
	    genreList.add("Rock/Various");
	    genreList.add("Salsa_music");
	    genreList.add("Ska");
	    genreList.add("Soca_music");
	    genreList.add("Soul");
	    genreList.add("soul_music");
	    genreList.add("Soul_music");
	    genreList.add("Soundtrack");
	    genreList.add("Southern_hip_hop");
	    genreList.add("Southern_Rap");
	    genreList.add("Spoken_word");
	    genreList.add("Spoken_Word");
	    genreList.add("Synthpop");
	    genreList.add("Techhouse");
	    genreList.add("Techno");
	    genreList.add("Thrashcore");
	    genreList.add("Thrash_metal");
	    genreList.add("Thrash_Metal");
	    genreList.add("Uplifting_Trance");
	    genreList.add("Urban");
	    genreList.add("Urban_contemporary_gospel");
	    genreList.add("Varied");
	    genreList.add("various");
	    genreList.add("Various");
	    genreList.add("Various.");
	    genreList.add("Various (an assortment of ");
	    genreList.add("Various / Christian");
	    genreList.add("Video_game_music");
	    genreList.add("West_coast_hip_hop");
	    genreList.add("World");
		
	    // create an ArrayAdaptar from the String Array
    	ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this, R.layout.locationtextview, genreList);
	    setListAdapter(dataAdapter);
	    ListView listView = getListView();
	    // enables filtering for the contents of the given ListView
	    listView.setTextFilterEnabled(true);
	    listView.setOnItemClickListener(new OnItemClickListener() {
		    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
			    Intent i = new Intent("");
			    String genreChoice = ((TextView) view).getText().toString();
			    i.setData(Uri.parse(genreChoice));
			    setResult(RESULT_OK, i);
		    	finish();
		    }
    	});
	}
}
